name: Taxon Request
description: Request a new taxon
title: "[Taxon]: "
labels: ["feature", "taxon"]
assignees:
  - ryanmwhitephd
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this taxon request!
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: false
 - type: textarea
    id: name
    attributes:
      label: Taxon Name
      description: Propose a name?
      placeholder: Tell us what you measure!
      value: "Measure.Taxon"
    validations:
      required: false
  
