name: Taxon Request
description: Request a new taxon
title: "[Taxon]: "
labels: ["feature", "taxon"]
assignees:
  - ryanmwhitephd
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this taxon request!
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: false
  - type: dropdown
    id: process
    attributes:
      label: What is the process type?
      multiple: false
      options:
        - Measure
        - Source
  - type: textarea
    id: measurand
    attributes:
      label: Measurand
      description: Provide a description of the measurand?
      placeholder: Tell us what you measure!
    validations:
      required: false
  - type: textarea
    id: quantitykind
    attributes:
      label: Kind of quantity
      description: Provide a kind of quantity for the measurand?
      placeholder: Tell us what you measure!
      value: "Length"
    validations:
      required: false
  - type: dropdown
    id: special
    attributes:
      label: Does the measurand require a special token?
      multiple: false
      options:
        - Ratio
        - Coefficient
        - Delta
        - Model
  - type: textarea
    id: name
    attributes:
      label: Taxon Name
      description: Propose a name?
      placeholder: Tell us what you measure!
      value: "Measure.Taxon"
    validations:
      required: false
  
